### ISSUE TITLE
Buffer.write() range error in createRequest()

### ISSUE THREAD

**Issue by 0x557269656C** [SylverFox/smb-enumerate-shares#1]
Within `createRequest()`, when `command === CLOSE` condition occurs an uncontrolled exception is raised:

```
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <= 24. Received 32
    at validateOffset (node:buffer:112:3)
    at Buffer.write (node:buffer:1073:7)
    at createRequest (/.../index.js:124:14)
    at module.exports (/.../node_modules/smb-enumerate-shares/index.js:257:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_OUT_OF_RANGE'
}
```
This is due to the fact that `structure` buffer being used is a 24 byte length buffer derived from:

```javascript
const requestStructures = {
        (...)
	[CLOSE]: '180000000000000000000000000000000000000000000000'
}
```

And because, `fileid.length` is being used to control the buffer's `write()`  maximum number of bytes to write option, this leads to a condition where `fileid.length` may be superior to `buf.length - offset`, because `fileid` is being  populated with a (at most) 32 byte buffer:

```javascript
fileid = result.slice(132, 148).toString('hex')
```

A suggested quick-fix is to ensure that within `createRequest()`, `structure.write()` operations enforce the buf.length - offset maximum number of bytes to write constrain, as in this example:

```javascript
structure.write(fileid, 8, structure.length - 8, 'hex')
```

**Comment by warpdesign** [comment]
I can confirm @0x557269656C's suggestion fixes the problem.
